language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm
  -
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --testdox

after_success:
  - bash <(curl -s https://codecov.io/bash)